-- MySQL Script generated by MySQL Workbench
-- Mon Jun 25 14:55:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sio` ;

-- -----------------------------------------------------
-- Schema sio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sio` DEFAULT CHARACTER SET utf8 ;
USE `sio` ;

-- -----------------------------------------------------
-- Table `sio`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`account` ;

CREATE TABLE IF NOT EXISTS `sio`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `email` VARCHAR(64) NULL COMMENT 'the max allowed is 64 byte',
  `password` CHAR(32) NOT NULL,
  `phone` CHAR(11) NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `phone_UNIQUE` ON `sio`.`account` (`phone` ASC);

CREATE INDEX `username` ON `sio`.`account` (`username` ASC);

CREATE UNIQUE INDEX `username_UNIQUE` ON `sio`.`account` (`username` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `sio`.`account` (`email` ASC);


-- -----------------------------------------------------
-- Table `sio`.`song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`song` ;

CREATE TABLE IF NOT EXISTS `sio`.`song` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `duration` INT NULL,
  `fee` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '收费',
  `album_id` INT NULL,
  `bitrate` INT NULL DEFAULT 128,
  `picture_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `name` ON `sio`.`song` (`name` ASC);

CREATE INDEX `album_id` ON `sio`.`song` (`album_id` ASC);


-- -----------------------------------------------------
-- Table `sio`.`artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`artist` ;

CREATE TABLE IF NOT EXISTS `sio`.`artist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `picture_id` INT NULL,
  `album_size` TINYINT NULL COMMENT '专辑总数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `name` ON `sio`.`artist` (`name` ASC);


-- -----------------------------------------------------
-- Table `sio`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`album` ;

CREATE TABLE IF NOT EXISTS `sio`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `artist_id` INT NOT NULL,
  `picture_id` INT NULL,
  `pub_time` DATETIME NULL,
  `size` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `name` ON `sio`.`album` (`name` ASC);

CREATE INDEX `artist_id` ON `sio`.`album` (`artist_id` ASC);


-- -----------------------------------------------------
-- Table `sio`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`tag` ;

CREATE TABLE IF NOT EXISTS `sio`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `brief` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sio`.`site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`site` ;

CREATE TABLE IF NOT EXISTS `sio`.`site` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sio`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`playlist` ;

CREATE TABLE IF NOT EXISTS `sio`.`playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `picture_id` INT NULL,
  `tracks_count` INT UNSIGNED NULL DEFAULT 0,
  `play_count` INT UNSIGNED NULL DEFAULT 0,
  `book_count` INT UNSIGNED NULL DEFAULT 0 COMMENT '订阅总数',
  `create_time` DATETIME NULL,
  `creator_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `name` ON `sio`.`playlist` (`name` ASC);

CREATE INDEX `creator_id` ON `sio`.`playlist` (`creator_id` ASC, `name` ASC);


-- -----------------------------------------------------
-- Table `sio`.`playlist_songs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`playlist_songs` ;

CREATE TABLE IF NOT EXISTS `sio`.`playlist_songs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playlist_id` INT NOT NULL,
  `song_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `playlist_id` ON `sio`.`playlist_songs` (`playlist_id` ASC);

CREATE INDEX `song_id` ON `sio`.`playlist_songs` (`song_id` ASC);


-- -----------------------------------------------------
-- Table `sio`.`song_artists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`song_artists` ;

CREATE TABLE IF NOT EXISTS `sio`.`song_artists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `song_id` INT NOT NULL,
  `artist_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `song_id` ON `sio`.`song_artists` (`song_id` ASC);

CREATE INDEX `artist_id` ON `sio`.`song_artists` (`artist_id` ASC);


-- -----------------------------------------------------
-- Table `sio`.`playlist_booked`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`playlist_booked` ;

CREATE TABLE IF NOT EXISTS `sio`.`playlist_booked` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playlist_id` INT NOT NULL,
  `booked_user_id` INT NOT NULL COMMENT '订阅者',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `playlist_id` ON `sio`.`playlist_booked` (`playlist_id` ASC);

CREATE INDEX `booked_user_id` ON `sio`.`playlist_booked` (`booked_user_id` ASC);


-- -----------------------------------------------------
-- Table `sio`.`song_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`song_tags` ;

CREATE TABLE IF NOT EXISTS `sio`.`song_tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `song_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `song_id` ON `sio`.`song_tags` (`song_id` ASC);

CREATE INDEX `tag_id` ON `sio`.`song_tags` (`tag_id` ASC);


-- -----------------------------------------------------
-- Table `sio`.`song_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`song_info` ;

CREATE TABLE IF NOT EXISTS `sio`.`song_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `song_id` INT NOT NULL,
  `favors` INT NOT NULL COMMENT '喜欢',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `song_id` ON `sio`.`song_info` (`song_id` ASC);


-- -----------------------------------------------------
-- Table `sio`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sio`.`picture` ;

CREATE TABLE IF NOT EXISTS `sio`.`picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `url` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '歌曲易变属性信息';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
